<div class="mobile-footer">
    <div class="social-links">
        <div class="links-container">
        <a class="social-acc-pic" href="https://www.facebook.com" target="_blank"> <img
                src="http://bangkok.loc/pub/static/version1521454206/frontend/Bangkok/default/en_US/images/facebook.png"
                alt="facebook-icon"> </a>
        <a class="social-acc-pic" href="https://www.instagram.com" target="_blank"> <img
                src="http://bangkok.loc/pub/static/version1521454206/frontend/Bangkok/default/en_US/images/instagram.png"
                alt="instagram-icon"> </a>
        <a class="social-acc-pic" href="https://www.youtube.com" target="_blank"> <img
                src="http://bangkok.loc/pub/static/version1521454206/frontend/Bangkok/default/en_US/images/youtube.png"
                alt="youtube-icon"> </a>
        <a class="social-acc-pic"> <img
                src="http://bangkok.loc/pub/static/version1521454206/frontend/Bangkok/default/en_US/images/empty-link.png"
                alt="youtube-icon"></a>
        </div>
    </div>
    <div class="general-subcategories">
        <div style="margin-bottom: 1rem;"><a href="#">WHERE TO BUY</a></div>
        <div style="margin-bottom: 1rem;"><a href="http://bangkok.loc/customer-care/">CUSTOMER CARE</a></div>
        <div style="margin-bottom: 1rem;"><a href="http://bangkok.loc/contact-us/">CONTACT US</a></div>
        <div><a href="http://bangkok.loc/policies/">POLICIES</a></div>
    </div>
</div>