<div class="mobile-footer">
    <div class="social-links">
        <span>Follow us</span>
        <div class="links-container">
        <a class="social-acc-pic" href="https://www.facebook.com" target="_blank"> <img
                src="<?php echo $block->getViewFileUrl("images/icons/homePage/Facebook.svg"); ?>"
                alt="facebook"> </a>
        <a class="social-acc-pic" href="https://www.instagram.com" target="_blank"> <img
                src="<?php echo $block->getViewFileUrl("images/icons/homePage/Instagram.svg"); ?>"
                alt="instagram"> </a>
        <a class="social-acc-pic" href="https://www.youtube.com" target="_blank"> <img
                src="<?php echo $block->getViewFileUrl("images/icons/homePage/youtube.svg"); ?>"
                alt="youtube"> </a>
        <a class="social-acc-pic"> <img
                src="<?php echo $block->getViewFileUrl("images/empty-link.png"); ?>"
                alt="add-link"></a>
        </div>
    </div>
    <div class="general-subcategories">
        <div><a href="http://bangkok.loc/where-to-buy/"><?= __('WHERE TO BUY')?></a></div>
        <div><a href="http://bangkok.loc/customer-care/"><?= __('CUSTOMER CARE')?></a></div>
        <div><a href="http://bangkok.loc/contact-us/"><?= __('CONTACT US')?></a></div>
        <div><a href="http://bangkok.loc/policies/"><?= __('POLICIES')?></a></div>
    </div>
</div>