<div class="mobile-footer">
    <div class="social-links">
        <span>Follow us</span>
        <div class="links-container">
        <a class="social-acc-pic" href="https://www.facebook.com" target="_blank"> <img
                src="<?php echo $block->getViewFileUrl("images/icons/homePage/Facebook.svg"); ?>"
                alt="facebook"> </a>
        <a class="social-acc-pic" href="https://www.instagram.com" target="_blank"> <img
                src="<?php echo $block->getViewFileUrl("images/icons/homePage/Instagram.svg"); ?>"
                alt="instagram"> </a>
        <a class="social-acc-pic" href="https://www.youtube.com" target="_blank"> <img
                src="<?php echo $block->getViewFileUrl("images/icons/homePage/youtube.svg"); ?>"
                alt="youtube"> </a>
        <a class="social-acc-pic"> <img
                src="<?php echo $block->getViewFileUrl("images/empty-link.png"); ?>"
                alt="add-link"></a>
        </div>
    </div>
    <div class="general-subcategories">
        <div><a href="<?= $block->getUrl('where-to-buy'); ?>"><?= __('WHERE TO BUY')?></a></div>
        <div><a href="<?= $block->getUrl('customer-care'); ?>"><?= __('CUSTOMER CARE')?></a></div>
        <div><a href="<?= $block->getUrl('contact-us'); ?>"><?= __('CONTACT US')?></a></div>
        <div><a href="<?= $block->getUrl('policies'); ?>"><?= __('POLICIES')?></a></div>
    </div>
    <span class="copyright">©2017 NUI Co. Ltd. All Rights Reserved</span>
</div>