<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div>
    <div>
        <span><a href=""><?php echo __('Women'); ?></a></span>
        <span><a href=""><?php echo __('Men'); ?></span>
        <span><a href=""><?php echo __('Girls'); ?></span>
    </div>
    <div>
        <div><a href=""><?php echo __('Collection'); ?></a></div>
        <div><a href=""><?php echo __('Promotion'); ?></a></div>
        <div><a href=""><?php echo __('Bags'); ?></a></div>
        <div><a href=""><?php echo __('Shoes'); ?></a></div>
        <div><a href=""><?php echo __('Accessories'); ?></a></div>
        <div><a href=""><?php echo __('Clothing'); ?></a></div>
    </div>
</div>