<?php /** @var \Encomage\Theme\Block\Html\Page\Sidebar\Categories $block */ ?>
<?php $categories = $block->getCategories(); ?>
<div class="left-menu">
    <?php if (!empty($categories)): ?>
        <div class="js-sidebar-categories">
            <div class="main-categories">
                <?php foreach ($categories as $category): ?>
                    <span class="font-less">
                         <a data-category-id="<?php echo $category->getId(); ?>"
                            class="js-sidebar-category js-no-link js-category-main"
                            href="">
                             <?php echo $category->getName(); ?>
                         </a>
                    </span>
                <?php endforeach; ?>
            </div>
            <div class="main-subcategories">
                <?php foreach ($categories as $child0): ?>
                    <?php if ($child0->hasChildren()): ?>
                        <?php foreach ($child0->getChildren() as $child1): ?>
                            <div>
                                <a data-category-id="<?php echo $child1->getId(); ?>"
                                   data-parent-id="<?php echo $child1->getParent()->getId(); ?>"
                                   class="js-sidebar-subcategories js-no-link js-category-child-1"
                                   href=""><?php echo $child1->getName(); ?></a>
                                <?php if ($child1->hasChildren()): ?>
                                    <ul>
                                        <?php foreach ($child1->getChildren() as $child2): ?>
                                            <li>
                                                <a data-category-id="<?php echo $child2->getId(); ?>"
                                                   data-parent-id="<?php echo $child2->getParent()->getId(); ?>"
                                                   class="js-sidebar-subcategories js-category-child-2"
                                                   href="<?php echo $child2->getName() ?>">
                                                    <?php echo $child2->getName(); ?>
                                                </a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
        {
            ".js-sidebar-categories": {
                "Encomage_Theme/js/sidebar/categories": {}
            }
        }
</script>