<?php
/** @var \Magento\Store\Block\Switcher $block */
?>

<div class="mobile-nav-switch-language">
    <?php foreach ($block->getStores() as $lang): ?>
        <div class="item <?php echo ($block->getStoreCode() == $lang->getCode()) ? 'active' : ''; ?>">
            <a href="#" data-post='<?php echo $block->getTargetStorePostData($lang) ?>'>
                <img src="<?php echo $this->getViewFileUrl('images/mobile/nav/languages/' . $lang->getCode() . '.png'); ?>">
            </a>
        </div>
    <?php endforeach; ?>
</div>