<?php /** @var Encomage\Stories\Block\Stories $block */ ?>

<div class="stories-content">
    <div>
        <a class="js-our-story-button cms-button-small active" href="#">Our Stories</a>
        <a class="js-your-stories-button cms-button-small " href="#">Your Stories</a>
        <?php if ($block->isCustomerLogged()) : ?>
            <a class="js-add-story-button btn-foursquare" href="<?= $block->escapeUrl($block->getAddUrl()); ?>" hidden>Add note</a>
        <?php endif; ?>
    </div>
    <div class="js-our-story-block">
        <?= /* @noEscape */ $block->getChildHtml('our.story.block'); ?>
    </div>
    <div class="js-your-stories-block" hidden>
        <?= /* @noEscape */ $block->getChildHtml('your.stories.block'); ?>
    </div>
</div>
<script type="text/x-magento-init">
            {
                ".stories-content": {
                    "Encomage_Stories/js/page-toggle": {}
                }
            }
</script>