<?php /** @var Encomage\Stories\Block\Stories $block */ ?>

<div class="stories-content">
    <div class="buttons-container">
        <a class="js-our-story-button story-button active" href="#"><?= __('Our Stories'); ?></a>
        <a class="js-your-stories-button story-button" href="#"><?= __('Your Stories'); ?></a>
        <?php if ($block->isCustomerLogged()) : ?>
            <a class="js-add-story-button add-story-button" href="<?= $block->escapeUrl($block->getAddUrl()); ?>"
               hidden><?= __('Add note'); ?></a>
        <?php endif; ?>
    </div>
    <div class="js-our-story-block our-story-block">
        <?= /* @noEscape */$block->getChildHtml('our.story.block'); ?>
    </div>
    <div class="js-your-stories-block your-stories-block" hidden>
        <?= /* @noEscape */$block->getChildHtml('your.stories.block'); ?>
    </div>
</div>
<script type="text/x-magento-init">
            {
                ".stories-content": {
                    "Encomage_Stories/js/page-toggle": {}
                }
            }

</script>