<?php /** @var Encomage\Stories\Block\Stories $block */ ?>

<div class="stories-content">
    <div>
        <a class="our-story-button cms-button-small" href="<?= '#'; ?>">test 1</a>
        <a class="your-stories-button cms-button-small active" href="<?= '#'; ?>">test 2</a>
    </div>
    <div class="our-story-block">
        <?= $block->getChildHtml('our.story.block'); ?>
    </div>
    <div class="your-stories-block">
        <?= $block->getChildHtml('your.stories.block'); ?>
    </div>
</div>
<!--<script type="text/x-magento-init">-->
<!--            {-->
<!--                ".stories-content": {-->
<!--                    "Magento_Stories/js/page-toggle": {}-->
<!--                }-->
<!--            }-->
<!--</script>-->