<?php
/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Options $block */
?>

<?php $options = $block->getOptionList(); ?>
<?php if ($options): ?>
    <?php foreach ($options as $option): ?>
<div class="tooltip wrapper product-item-tooltip">
  <div>
      <div>

          <div class="label"><?= $block->escapeHtml($option['label']) ?></div>
          <div class="values">
              <?php if (is_array($option['value'])): ?>
              <?= /* @noEscape */ nl2br(implode("\n", $option['value'])) ?>
              <?php else: ?>
              <?= /* @noEscape */ $option['value'] ?>
              <?php endif; ?>
          </div>

      </div>
  </div>
</div>
    <?php endforeach; ?>
<?php endif ?>

