<?php
/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Options $block */
?>

<?php $options = $block->getOptionList(); ?>
<?php if ($options): ?>
<div class="tooltip wrapper product-item-tooltip">
  <div>
      <dl>
          <?php foreach ($options as $option): ?>
          <dt class="label"><?= $block->escapeHtml($option['label']) ?></dt>
          <dd class="values">
              <?php if (is_array($option['value'])): ?>
              <?= /* @noEscape */ nl2br(implode("\n", $option['value'])) ?>
              <?php else: ?>
              <?= /* @noEscape */ $option['value'] ?>
              <?php endif; ?>
          </dd>
          <?php endforeach; ?>
      </dl>
  </div>
</div>
<?php endif ?>
