<?php
/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="product-name-wsl">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
       title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
       class="product-item-link">
        <?= $block->escapeHtml($product->getName() . '' . $product->getSku()) ?>
    </a>
</div>
