<?php
/* @var \Encomage\Wishlist\Block\Customer\Wishlist\Item\Option $block */
?>
<?php $option = $block->getOption(); ?>
<?php if ($option): ?>
    <div class="wrapper <?= $block->getCssClass() ?>">
        <div class="label"><?= $block->escapeHtml(__($option['label'])) ?></div>
        <div class="values"><?= $block->escapeHtml(__($option['value'])) ?></div>
        <?php if(!empty($option['rgb_code'])) : ?>
            <div class="rgb" style="background:<?=$option['value']?>;"></div>
        <?php endif;?>
    </div>
<?php endif ?>
