<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<div class="sidebar-menu">
    <?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
    <?php if ($block->isHomePage()): ?>
    <strong class="logo">
        <?php else: ?>
        <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */
        $storeName ?>">
            <?php endif ?>
            <img src="<?= /* @escapeNotVerified */
            $block->getLogoSrc() ?>"
                 alt="<?= /* @escapeNotVerified */
                 $block->getLogoAlt() ?>"
                <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
            <?php if ($block->isHomePage()): ?>
    </strong>
<?php else: ?>
    </a>
<?php endif ?>
</div>
