<?php /** @var \Magento\Catalog\Block\Category\View $block */

/** @var \Encomage\Catalog\Helper\Data $helper */
$helper = $this->helper('Encomage\Catalog\Helper\Data');
/** @var  $categoryViewBlock \Magento\Catalog\Block\Category\View */
$categoryViewBlock = $block->getLayout()->getBlock('category.products');

?>
<?php if ($categoryViewBlock->getCurrentCategory()): ?>
    <div class="catalog-category-empty cms-coming-soon-category">
        <?= $block->getChildHtml() ?>
        <div class="notify-input-container">
            <form action="<?= $helper->getNotifyMeEmptyCategoryUrl($categoryViewBlock->getCurrentCategory()) ?>"
                  method="post">
                <input class="input-notify-email"
                       name="notify-email" type="email" required="required" placeholder="<?= $block->getPlaceholder() ?>"/>
                <button type="submit" class="cms-button-small" type="button"><?= $block->getLabel() ?></button>
            </form>
        </div>
    </div>
<?php endif; ?>