<?php /** @var Encomage\Stories\Block\Stories\YourStories $block */
$_collection = $block->storiesCollection();
$items = $_collection->getItems();
$_collectionSize = $_collection->getTotalCount();
?>
<div class="your-stories-container">
    <?php if ($_collectionSize) : ?>
        <div class="your-stories-content">
            <?php foreach ($items as $story) : ?>
                <?= $story->getContent(); ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
