<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>

<h2 class="mobile-my-account-title"><?= __('My account');?></h2>
<a href="<?= $block->escapeUrl($block->getUrl('sales/order/history', ['_secure' => true])); ?>"><?php echo __('My orders') ?></a>
<a href="<?= $block->escapeUrl($block->getUrl('nupoints', ['_secure' => true])); ?>"><?php echo __('My NuPoints') ?></a>
<a href="<?= $block->escapeUrl($block->getUrl('wishlist', ['_secure' => true])); ?>"><?php echo __('My wishlist') ?></a>

<div data-mage-init='{"accordion":{
"openedState": "active",
"collapsible": true,
"active": false,
"multipleCollapsible": true}}'>
    <span href="#" data-role="collapsible" class="open-account-details">
        <?= __('My account details (EDIT)'); ?>
    </span>
    <div class="customer-account-dashboard" data-role="content">
        <?= $block->getChildHtml('customer_account_dashboard_information') ?>
        <?= $block->getChildHtml('customer_account_dashboard_addresses') ?>
    </div>
</div>