<?php /** @var $block Encomage\Stories\Block\Stories\YourStories\Add */ ?>
<div class="add-story-content" data-mage-init='{"Encomage_Stories/js/add-story":{}}'>
    <form id="save-story-form" enctype="multipart/form-data" action="<?= $block->escapeUrl($block->getUrl('stories/yourstories/save')); ?>" method="post" data-hasrequired="* Required Fields">
        <fieldset class="fieldset story-fieldset">
            <div class="field story-image-uploader required">
                <div class="js-cropper attach-file"></div>
                <input hidden required="true" class="js-attach-file" type="text" id="story_image" name="story_image">
                <span class="js-image-upload-button image-upload-button"><?= __('Select picture') ?></span>
            </div>
            <div class="story-info">
                <p class="story-customer-name js-customer-name"></p>
                <p class="story-date-create"><?= $block->getDate(); ?></p>
            </div>
            <div class="field story-content required">
                <textarea required="true"
                          class="story-textarea"
                          id="content"
                          name="content"
                          placeholder="<?= __('Start writing your story'); ?>..."></textarea>
            </div>
            <span class="save-button"><?= /* @escapeNotVerified */ __('Publish'); ?></span>
        </fieldset>
    </form>
    <div class="save-message-modal">
        <p><?= /* @escapeNotVerified */ __('Your story will be approved in the near future.'); ?></p>
    </div>
</div>