<?php
/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?= $block->escapeHtml(__('Don`t have an account ? ')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>"
                   class="action create primary">
                    <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
                </a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
