<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">

    <div class="post-content desktop">
        <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) : ?>
            <div class="post-ftimg-hld">
                <a href="<?= $_postUrl ?>" title="<?= $_postName ?>">
                    <img src="<?= $featuredImage ?>" alt="<?= $_postName ?>" />
                </a>
            </div>
            <?php endif; ?>

        </div>
    </div>
    <div class="post-footer desktop">
        <h2 class="post-title">
            <a class="post-item-link"
               href="<?= $_postUrl ?>">
                <?= $_postName; ?>
            </a>
        </h2>
    </div>

    <div class="post-content mobile">
        <h2 class="post-title">
            <?= $_postName; ?>
        </h2>
        <div class="post-description clearfix">
            <div class="post-text-hld">
                <?php echo $block->getContent() ?>
            </div>
            <?= $block->getChildBlock('blog.post.product.items')->setPost($_post)->toHtml(); ?>
        </div>
    </div>
</li>