<?php

use Encomage\Checkout\Block\Cart\Item\Renderer\Options;
use Magento\Msrp\Helper\Data;
use Magento\Catalog\Model\Product\Type;
use Magento\Framework\View\Element\Template;

/** @var \Encomage\Checkout\Block\Cart\Item\Renderer $block */

/** @var \Magento\Quote\Model\Quote\Item $_item */
$_item    = $block->getItem();
$product  = $_item->getProduct();
$_options = null;
$qtyHtml  = null;


if ($_item->getProductType() === Type::TYPE_SIMPLE) {
    $_options = $block->getOptionList();
    $qtyHtml  = $block->getLayout()
                      ->createBlock(Template::class)
                      ->setTemplate('Magento_Checkout::cart/item/renderer/qty.phtml')
                      ->setItem($_item)
                      ->setRendererBlock($block)
                      ->toHtml();
} elseif ($_item->getProductType() === 'configurable') {
    $_options = $block->colorOption();

    $qtyHtml  = $block->getLayout()
                      ->createBlock(Template::class)
                      ->setTemplate('Magento_Checkout::cart/item/renderer/qty.phtml')
                      ->setItem($_item)
                      ->setRendererBlock($block)
                      ->toHtml();
}
//$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper       = $this->helper(Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<div class="cart item">
    <div class="item-info">
        <div data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()): ?>
            <a href="<?= /* @escapeNotVerified */
            $block->getProductUrl() ?>"
               title="<?= $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else: ?>
                <div class="product-item-photo">
                    <?php endif; ?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                    <?php if ($block->hasProductUrl()): ?>
            </a>
            <?php else: ?>
        </div>
        <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= /* @escapeNotVerified */
                    $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options): ?>
                <?= $block->getLayout()
                          ->createBlock(Options::class)
                          ->setQtyHtml($qtyHtml)
                          ->setOptions($_options)
                          ->setRendererBlock($block)
                          ->toHtml(); ?>
            <?php else: ?>
                <?= $qtyHtml; ?>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @escapeNotVerified */
                    $message['type'] ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </div>

    <?php if ($canApplyMsrp): ?>
        <div class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */
                        __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */
                    ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */
                    $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */
                    $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */
                            __("What's this?") ?></span>
                    </a>
                </span>
        </div>
    <?php else: ?>
        <div class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </div>
    <?php endif; ?>


    <div class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </div>
</div>
<div class="item-actions">
    <div colspan="100">
        <div class="actions-toolbar">
            <?= /* @escapeNotVerified */
            $block->getActions($_item) ?>
        </div>
    </div>
</div>
