<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<?= $block->getChildHtml('form_before') ?>
<h1 class="page-heading"><?= /* @escapeNotVerified */ __('My shopping bag'); ?></h1>
<?= $block->getChildHtml('checkout.cart.form.content'); ?>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

