<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php
$addressInfo = $block->getShippingAddress();
$country = $block->getCountryNameByCode();
?>
<div class="checkout-success">
    <h2><?= __('Thank you!') ?> <br><?= __('Your order is successfull') ?></h2>
    <div class="top-block-success">
        <?php if ($block->getOrderId()): ?>
            <?php if ($block->getCanViewOrder()) : ?>
                <p class="order-number"><?= __('Order No. is %1.', $block->getOrderId()) ?></p>
            <?php endif; ?>
            <p><?= __('An email receipt including the details about your invoice') ?></p>
            <p><?= __('has been sent to  %1', $addressInfo['email']) ?></p>

            <p class="bank-transfer-info"><?= __('Please transfer payment to'); ?></p>
            <p><?= __('1. Kasikorn Bank Account number  934-100-0804'); ?></p>
            <p><?= __('Account name: NUI company Limited'); ?></p>
            <p><?= __('Brunch:  Nana Neua. code. 0063'); ?></p>
            <p><?= __('2. Bank of Ayutthaya'); ?></p>
            <p><?= __('Account number 769-000-1317 Current account'); ?></p>
            <p><?= __('Account name: NUI company Limited.'); ?></p>
            <p><?= __('3. Promtpay - Phone Number 087-500-5222'); ?></p>
            <p><?= __('Account name: Samusha Sutsoong'); ?></p>
        <?php endif; ?>
</div>
<div class="bottom-block-success">
        <p><?= __('Shipping Address') ?></p>
        <p><?= __('This order will shipped to:') ?></p>

        <p><span><?= __('Customer Name') ?></span> &nbsp;&nbsp;
            <?= $addressInfo['firstname'] ?>&nbsp;<span><?= $addressInfo['lastname'] ?></span></p>
        <p><span><?= __('Adress') ?></span> &nbsp;&nbsp;<?= $addressInfo['street'] ?></p>
        <p><span><?= __('Adress 2') ?></span></p>
        <p><?= $country ?>,&nbsp<span><?= $addressInfo['city'] ?></span></p>
    </div>
</div>
