<?php
/**
 * @var $block Encomage\Careers\Block\Listing;
 */
$_collection = $block->getCareersCollection();
?>
<div class="careers-listing-content">
    <?= $block->getVideoCmsBlock(); ?>
    <?= $block->getImageCmsBlock(); ?>
    <p>Available position:</p>
    <?php foreach ($_collection as $item) : ?>
        <?php if ($item->getStatus() == 1) : ?>
            title: <?php echo $item->getTitle(); ?>
            <a href="<?php echo $block->getUrlView($item->getId()); ?>">more</a> <br/>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
