<?php
/**
 * @var $block Encomage\Careers\Block\Listing;
 */
$_collection = $block->getCareersCollection();
?>
<div class="careers-listing-content">
    <?= $block->getVideoCmsBlock(); ?>
    <?= $block->getImageCmsBlock(); ?>
    <p class="careers-listing-title"><?= /** @escapeNotVerified */ __('Available positions'); ?>:</p>
    <?php foreach ($_collection as $item) : ?>
        <?php if ($item->getStatus() == 1) : ?>
            <div class="short-description-container">
                <p class="short-description-title"><?= /* @escapeNotVerified */  __($item->getTitle()); ?></p>
                <p class="short-description"><?= $block->escapeHtml($item->getShortDescription()); ?>
                <a class="morelink" href="<?= $block->escapeUrl($block->getUrlView($item->getId())); ?>"><?= /** @escapeNotVerified */ __('more'); ?></a>
                    <br/>
                </p>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<script>

</script>
