<?php
/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <h2><?= __('Sign in');?></h2>
        <?= $block->getChildHtml('social-login-popup-authentication-social-login')?>
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login">
                <div class="field email required">
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email"
                               type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               data-validate="{required:true, 'validate-email':true}" placeholder="<?=__('Email')?>">
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?>
                            autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               data-validate="{required:true}" placeholder="<?=__('Password')?>">
                        <div class="customer-show-password">
                            <label for="customer-show-password" class="label"
                                   data-mage-init='{"Magento_Customer/js/customer-sign-in":{}}'>
                                <input type="checkbox" name="specials_offers"
                                       title="<?php echo __('Show password') ?>"
                                       id="customer-show-password"
                                       class="checkbox"
                                       style="display: none">
                                <span><?php echo __('Show password') ?></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="checkbox-block checkbox-block-mobile">
                    <div class="field choice">
                        <label for="keep_signed_in_mob" class="label">
                            <input type="checkbox" name="keep_signed_in_mob" title="<?= __("Keep me signed in");?>" id="keep_signed_in_mob" checked="checked" class="checkbox">
                            <span></span><span><?= __("Keep me signed in");?></span>
                        </label>
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary">
                        <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                            <span><?= $block->escapeHtml(__('Forgot Password?')) ?></span>
                        </a>
                        <div class="checkbox-block checkbox-block-desktop">
                            <div class="field choice">
                                <label for="keep_signed_in" class="label">
                                    <input type="checkbox" name="keep_signed_in" title="<?= __("Keep me signed in");?>" id="keep_signed_in" checked="checked" class="checkbox">
                                    <span></span><span><?= __("Keep me signed in");?></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
