<?php
/** @var $block \Encomage\Catalog\Block\Product\View\QuestionAboutSize */

?>
<?php if ($block->isShowQuestion()): ?>
    <div class="message js-message" <?= ($block->getProduct()->getTypeId() == 'configurable') ? 'style="display:none;"' : ''; ?>>
        <p><?php echo __('Have you worn these shoes before?'); ?></p>
        <div class="radio-box">
            <label for="yes">
                <input type="radio" id="yes"
                       name="answer" value="yes" class="js-answer">
                <span></span><span class="choose-yes"><?php echo __('Yes'); ?></span></label>

            <label for="no">
                <input type="radio" id="no" class="js-answer js-show-model"
                       name="answer" value="no">
                <span></span><span class="choose-no"><?php echo __('No'); ?></span></label>
        </div>
    </div>
    <div id="product-message-box-popup" style="display: none">
        <p><?= __('If you have not worn this shoe before, please let us help you make the best choice for perfect fit by clicking Open Live Chat to speak with a person nuAmbassador.'); ?></p>
        <p><?= __('However, if you are sure about your size, and do not have time to speak with our nuAmbassador, you may click Add to bag now.'); ?></p>
    </div>
    <script type="text/x-magento-init">
    {
        "#product-message-box-popup": {
            "Magento_Catalog/js/add-to-cart-question": {}
        }
    }
    </script>
<?php endif; ?>