<?php
/** @var $block \Encomage\Catalog\Block\Product\View\Qty */
?>

<?php if ($block->shouldRenderQuantity()): ?>
    <div class="field qty">
        <label class="label" for="qty"><span></span></label>
        <div class="control">
            <input type="number"
                   name="qty"
                   id="qty"
                   value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                   class="input-text qty"
                   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
            />
        </div>
    </div>
<?php endif; ?>