<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div>
    <div><a href="#"><?php echo __('Inspiration'); ?></a></div>
    <div><a href="#"><?php echo __('Customer care'); ?></a></div>
    <div><a href="#"><?php echo __('Product care'); ?></a></div>
    <div><a href="#"><?php echo __('Contact us'); ?></a></div>
    <div><a href="#"><?php echo __('Career'); ?></a></div>
    <div>
        <span>FB</span>
        <span>Inst</span>
        <span>youtube</span>
    </div>
    <div><a href="#"><?php echo __('Policies'); ?></a></div>
</div>