<?php
/** @var $block \Encomage\Nupoints\Block\Catalog\Product\View\NupointsRedeem */
?>
<div class="catalog-product-view-nupoints-redeem view-nupoints-redeem"
     data-mage-init='{"Encomage_Nupoints/js/catalog/product/view/nupoints-redeem":{"nupointsRedeemUrl":"nupoints/catalog/nupointsRedeem"}}'>
    <div>
        <span><?= __('Points available to redeem'); ?>:</span>
        <span class="js-customer-nupoints-balance"></span>
        <span><?= __('nuPoints'); ?></span>
    </div>
    <div>
        <span><?= __('Choose from this options'); ?></span>
        <p class="mobile-to-redeem"><?= __('Choose from this options'); ?></p>
        <div class="js-select-custom js-nupoints-rates select-redeem"
             data-mage-init='{"customSelect":{"placeholder":"<?= __('Redeem the following number of points'); ?>"}}'>
            <div class="js-list">
                <?php foreach ($block->getAvailableRedeemList() as $item): ?>
                    <?php $product = $item['product']; ?>
                    <div
                        class="js-option" <?= ($block->getSelectedOption() == $item['nupoints']) ? 'selected="true"' : ''; ?>
                        data-option-value="<?= $item['nupoints'] ?>">
                        <div class="option-container">
                            <?php if ($product) : ?>
                                <div class="image-container">
                                    <?php $image = $block->getImage($product, 'nupoint_related_product'); ?>
                                    <?= $image->toHtml(); ?>
                                </div>
                            <?php endif; ?>
                            <div class="text-container">
                                <p><?= __('%1 nuPoints for (฿) %2 off', $item['nupoints'], $item['money']); ?></p>
                                <?php if ($product) : ?>
                                    <p><?= __('Free a product'); ?> <?= $product->getName(); ?></p>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <span><button class="js-customer-nuponts-redeem"><span><?= __('Redeem'); ?></span></button></span>
        </div>
    </div>
</div>
