<?php
/** @var $block \Encomage\Nupoints\Block\Catalog\Product\View\NupointsRedeem */
?>
<div class="catalog-product-view-nupoints-redeem view-nupoints-redeem"
     data-mage-init='{"Encomage_Nupoints/js/catalog/product/view/nupoints-redeem":{"nupointsRedeemUrl":"nupoints/catalog/nupointsRedeem"}}'>
    <div>
        <span><?= __('Your balance is'); ?></span>
        <span class="js-customer-nupoints-balance"></span>
        <span><?= __('nuPoints'); ?></span>
    </div>
    <div>
        <span><?= __('I want to redeem'); ?></span>
        <p class="mobile-to-redeem"><?= __('I want to redeem'); ?></p>
        <div class="js-select-custom js-nupoints-rates select-redeem"
             data-mage-init='{"customSelect":{"placeholder":"<?= __('Choose your redeem'); ?>"}}'>
            <div class="js-list">
                <?php foreach ($block->getAvailableRedeemList() as $item): ?>
                    <?php $product = $item['product']; ?>
                    <?php if ($product) : ?>
                        <?php $image = $block->getImage($product, 'nupoint_related_product'); ?>
                        <div
                            class="js-option" <?= ($block->getSelectedOption() == $item['nupoints']) ? 'selected="true"' : ''; ?>
                            data-option-value="<?= $item['nupoints'] ?>">
                            <div class="option-container">
                                <div class="image-container">
                                    <?= $image->toHtml(); ?>
                                </div>
                                <div class="text-container">
                                    <p><?= __('%1 nuPoints for (฿) %2 off', $item['nupoints'], $item['money']); ?></p>
                                    <p><?= __('Free a product'); ?> <?= $product->getName(); ?></p>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <span><button class="js-customer-nuponts-redeem"><span><?= __('Redeem'); ?></span></button></span>
        </div>
    </div>
</div>
