<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div class="left-menu">
    <div class="main-categories">
        <span class="font-less active-category"><a href=""><?php echo __('Women'); ?></a></span>
        <span class="font-less"><a href=""><?php echo __('Men'); ?></a></span>
        <span class="font-less"><a href=""><?php echo __('Girls'); ?></a></span>
    </div>
    <div class="main-subcategories">
        <div><a href=""><?php echo __('Collection'); ?></a></div>
        <div><a href=""><?php echo __('Promotion'); ?></a></div>
        <div><a href=""><?php echo __('Bags'); ?></a></div>
        <div><a href=""><?php echo __('Shoes'); ?></a></div>
        <div><a href=""><?php echo __('Accessories'); ?></a></div>
        <div><a href=""><?php echo __('Clothing'); ?></a></div>
    </div>
</div>