<?php
/** @var \Encomage\Customer\Block\Address\Edit $block */
?>
<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate-<?= $block->getAddressId(); ?>"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"addressValidation": {}}'>


    <input type="hidden"
           name="<?= ($block->isShippingTypeRender()) ? 'default_shipping' : 'default_billing' ?>"
           value="1">

    <?php if($block->isShippingTypeRender() && !$block->getAddress()->getId()):?>
        <div class="checkbox-block">
            <div class="field choice">
                <label for="use_default_address" class="label">
                    <input type="checkbox" id="use_default_address" name="use_default_address" value="1" class="checkbox">
                    <span></span><span><?= $block->escapeHtml(__('Same as default address')) ?></span>
                </label>
            </div>
        </div>
        <div class="or">
            <span><?= __('or'); ?></span>
        </div>

    <?php endif; ?>


    <?php if (!$block->getAddress()->getId()): ?>
        <div class="legend legend-contact-info">
            <span><?= $block->escapeHtml(__('Add another shipping information')) ?></span>
        </div>
    <?php endif; ?>

    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <input type="hidden" name="firstname"
               value="<?= $block->getCustomer()->getFirstname(); ?>">
        <input type="hidden" name="lastname"
               value="<?= $block->getCustomer()->getLastname(); ?>">
        <input type="hidden" name="telephone"
               value="<?= $block->getAddress()->getTelephone(); ?>">
        <div class="field country required">
            <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                       id="street_1-<?= $block->getAddressType();?>"
                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                       placeholder="<?= __('Street Address'); ?>"/>
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */
                            $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                       id="street_<?= /* @noEscape */
                                       $_i + 1 . '-' . $block->getAddressType() ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                                       placeholder="<?= __('Street Address 2'); ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <div class="field city required">
            <div class="control">
                <input type="text"
                       name="city"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>"
                       id="city-<?= $block->getAddressType();?>" placeholder="<?= __('City'); ?>">
            </div>
        </div>
        <div class="field zip required">
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                       id="zip-<?= $block->getAddressType();?>" placeholder="<?= __('Zip/Postal Code'); ?>"
                       class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
    </fieldset>
</form>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */
    $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate-<?= $block->getAddressId(); ?>",
                "regionJson": <?= /* @noEscape */
    $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */
    $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }

</script>
