<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php $product = $block->getProduct(); ?>
<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */
      $block->getWidth() ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */
          ($block->getRatio() * 100) ?>%;">
        <div class="image-block">
        <img class="product-image-photo"
            <?= /* @escapeNotVerified */
            $block->getCustomAttributes() ?>
             src="<?= /* @escapeNotVerified */
             $block->getImageUrl() ?>"
             width="<?= /* @escapeNotVerified */
             $block->getResizedImageWidth() ?>"
             height="<?= /* @escapeNotVerified */
             $block->getResizedImageHeight() ?>"
             alt="<?= /* @escapeNotVerified */
             $block->stripTags($block->getLabel(), null, true) ?>"/>

            <?php if ($product->getLimited()): ?>
                <span class="product-note-info">Limited</span>
            <?php endif; ?>
            <?php if ($block->getNew()): ?>
                <span class="product-note-status">New</span>
            <?php endif; ?>
            <?php if ($product->getPopular()): ?>
                <span class="popular-products">Popular</span>
            <?php endif; ?>
    </span>
    </div>
</span>
