<?php

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_catalogHelper = $this->helper('Encomage\Catalog\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <?= $block->getChildHtml('category.empty'); ?>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */
    $viewMode ?> products-<?= /* @escapeNotVerified */
    $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $productChildren = $_product->getTypeInstance()->getUsedProducts($_product);
                $checkProductConfig = [];
                foreach ($productChildren as $productChild):?>
                <?php
                    if (in_array($productChild->getColor(), $checkProductConfig)) {
                        continue;
                    } else {
                        $checkProductConfig[] = $productChild->getColor();
                    }
                    ?>
                    <?php if ($_catalogHelper->checkProductStockStatusForProductNotify($productChildren) ||
                        $_catalogHelper->getProductStockStatus($productChild->getId())): ?>
                        <?= /* @escapeNotVerified */
                        ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($productChild, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= /* @escapeNotVerified */
                            $productChild->getProductUrl() ?>" class="product photo product-item-photo"
                               tabindex="-1"> <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php echo $_productNameStripped = $block->stripTags($productChild->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
                                       $productChild->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($productChild, $productChild->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?php if (!$_product->isAvailable()): ?>
                                    <div class="product-price-row">
                                        <div class="price-box">
                                            <span class="product-out-of-stock"><?= /* @escapeNotVerified */
                                                __('Out of stock') ?></span>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <div class="product-price-row">
                                        <?= $block->getProductPrice($productChild) ?>
                                        <?php if ($productChild->getClearance()): ?>
                                            <div class="clearance-att"><?= __('Clearance'); ?></div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?= $block->getProductDetailsHtml($productChild) ?>
                            </div>
                        </div>
                        <?= ($iterator == $_productCollection->count() + 1) ? '</li>' : '' ?>
                    <?php endif; ?>

                <?php endforeach; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
