<?php
/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>

<div class="cart main actions">
    <?php if ($block->getContinueShoppingUrl()): ?>
        <a class="action continue"
           href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
           title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
            <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
        </a>
    <?php endif; ?>
</div>
