<?php /** @var $block \Encomage\Theme\Block\Slider */ ?>
<div>
    <div class="mp-owl-carousel owl-carousel">
        <?php foreach ($block->getSliders() as $slider): ?>
            <div class="item js-slider-image">
                <img src="<?= $slider->getBannerUrl(); ?>" <?= ($slider->getMobileUploadFile()) ? 'data-slider-desktop-img' : ''; ?>
                     alt="img">
                <?php if ($slider->getMobileUploadFile()): ?>
                    <img src="<?= $slider->getBannerUrl(true); ?>" data-slider-mobile-img alt="img">
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".mp-owl-carousel": {
            "slider": <?php echo $block->getConfig(); ?>
        }
    }

</script>