<?php
/** @var \Encomage\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses">
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Address Information')) ?></span>
            </strong>
            <div class="box-content">
                <div class="adress">
                    <span><?= __('Address 1:'); ?></span>
                </div>
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
            <div data-mage-init='{"customerAddressEdit":{}}'>
                <div data-role="content">
                    <?= $block->getAddressEditBillingFormHtml(); ?>
                </div>
                <div class="box-actions">
                    <a class="action edit js-edit" data-role="collapsible" href="#"
                       data-ui-id="default-billing-edit-link">
                        <span><?= $block->escapeHtml(__('Edit Address')) ?></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Shipping Address Information')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>

            <div data-mage-init='{"customerAddressEdit":{}}'>
                <div data-role="content">
                    <?= $block->getAddressEditShippingFormHtml(); ?>
                </div>
                <div class="box-actions">
                    <a class="action edit js-edit" data-role="collapsible" href="#"
                       data-ui-id="default-billing-edit-link">
                        <span><?= $block->escapeHtml(__('Edit Address')) ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
