<?php

use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Model\Data\Option;


/** @var \Encomage\Customer\Model\Data\Customer $customer */
$customer = $block->getCustomer();

$LineId = $customer->getCustomAttribute('line_id');


/** @var Gender $_gender */
$_gender = $block->getLayout()->createBlock(Gender::class);

$genderCodeId = $customer->getGender();

$options = $_gender->getGenderOptions();

/** @var Option[] $customerGender */
$customerGender = array_filter($options, static function (Option $item) use ($genderCodeId) {
    return $item->getValue() === $genderCodeId;
});

if ( ! empty($customerGender)) {
    $customerGender = reset($customerGender);
}


?>
<div class="block block-dashboard-info">
    <div class="block-content">
        <div class="box box-information">
            <div class="box-content">
                <table>
                    <tr>
                        <th><?= __('First Name') ?></th>
                        <td><?= $customer->getFirstname() ?></td>
                    </tr>
                    <tr>
                        <th><?= __('Last Name') ?></th>
                        <td><?= $customer->getLastname() ?></td>
                    </tr>
                    <tr>
                        <th><?= __('Email') ?></th>
                        <td><?= $customer->getEmail() ?></td>
                    </tr>
                    <tr>
                        <th class="line-id"><?= __('Line Id') ?></th>
                        <td><?= $LineId ? $LineId->getValue() : '' ?></td>
                    </tr>
                    <tr>
                        <th><?= __('Date of Birth') ?></th>
                        <td><?= $block->escapeHtml($customer->getDob()) ?></td>
                    </tr>
                    <?php if ($_gender->isEnabled()): ?>
                        <tr>
                            <th><?= __('Gender') ?></th>
                            <td><?= $customerGender ? $block->escapeHtml(__($customerGender->getLabel())) : '' ?></td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra') ?>
                </div>
                <div class="box-actions">
                    <a class="action edit"
                       href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="box-actions">
        <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
            <span><?= $block->escapeHtml(__('Edit Profile')) ?></span>
        </a>
    </div>
</div>
