<?php
/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <span><?= __('Name') ?></span><?= $block->getName() ?><br>
                    <span><?= __('Lastname') ?></span><?= $block->getLastname()?><br>
                    <span><?= __('Email') ?></span><?= $block->getEmail() ?><br>
                    <span><?= __('Country') ?></span><?=__($block->getCountryName())?><br>
                    <span><?= __('Mobile') ?></span><?=$block->getTelephone()?><br>
                    <span><?= __('Line Id') ?></span><?=$block->getLineId()?><br>
                    <span><?= __('Date of Birth') ?></span><?= $block->getDob() ?><br>
                    <span><?= __('Gender') ?></span><?= __($block->getGender())?><br>
                </p>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra') ?>
                </div>
                <div class="box-actions">
                    <a class="action edit"
                       href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
