<?php
$_item = $block->getItem();
$rendererBlock = $block->getRendererBlock();
?>
<div class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
    <div class="field qty">
        <label class="label" for="cart-<?= /* @escapeNotVerified */
        $_item->getId() ?>-qty">
            <span><?php echo /* @escapeNotVerified */ __('Qty');?></span>
        </label>
        <div class="control qty">
            <span class="qty-reduce"><span>-</span></span>
            <input id="cart-<?= /* @escapeNotVerified */
            $_item->getId() ?>-qty"
                   name="cart[<?= /* @escapeNotVerified */
                   $_item->getId() ?>][qty]"
                   data-cart-item-id="<?= /* @escapeNotVerified */
                   $_item->getSku() ?>"
                   value="<?= /* @escapeNotVerified */ $rendererBlock->getQty() ?>"
                   type="number"
                   size="4"
                   title="<?= $block->escapeHtml(__('Qty')) ?>"
                   class="input-text qty"
                   data-validate="{required:true,'validate-greater-than-zero':true}"
                   data-role="cart-item-qty"/>
            <span class="qty-enhance "><span>+</span></span>
        </div>
    </div>
</div>