<?php /** @var $block \Encomage\Theme\Block\Slider */?>
<div>
	<div class="mp-owl-carousel owl-carousel">
		<?php foreach ($block->getSliders() as $slider): ?>
			<?php $url = $slider->getUrl() ? $slider->getUrl() : '#'?>
			<div class="item"><a href="<?php echo $url ; ?>"><img src="<?php echo $slider->getBannerUrl(); ?>" alt="img"></a></div>
		<?php endforeach; ?>
	</div>
</div>

<script type="text/x-magento-init">
    {
        ".mp-owl-carousel": {
            "slider": <?php echo $this->getConfig();?>
        }
    }
</script>