<?php
/** @var  $block \Encomage\Customer\Block\Account\TopLinks */
?>
<li class="switcher customer-links minicart-wrapper" data-block="my-account-link" data-bind="scope: 'customer_top_link_content'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script>
        window.store = <?= $block->getConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='my-account-link']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
        }
    }
    </script>
</li>
