<?php
/** @var Encomage\Nupoints\Block\Customer\Nupoints $block */
?>
<div class="points-container">
    <h2><?= __('MY nuPoints'); ?></h2>
    <p class="points-balance-title"><?= __('Rewards information'); ?></p>
    <p class="points-balance"><?= sprintf(__('Your balance is %s nuPoints'), '<span class="js-my-nupoints"></span>'); ?></p>
<?= $block->getChildHtml('block_reward_point_details'); ?>
</div>
<div class="box-actions">
    <a class="action edit"
       href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>">
        <?= $block->escapeHtml(__('Back')) ?></span>
    </a>
</div>

<script type="text/x-magento-init">
        {
            ".js-my-nupoints": {
                "Encomage_Nupoints/js/customer/my-nupoints": {}
            },
            ".js-open":{
            "Encomage_Nupoints/js/customer/points-popup": {}
            }
        }
</script>